// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
package RE_07_2412_Assignment2_Group_1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

// class AppTest {

//     @Test


// }
